version: '3.8'

services:
  backend:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
