import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
// eslint-disable-next-line no-restricted-globals
precacheAndRoute(self.__WB_MANIFEST);

// eslint-disable-next-line no-restricted-globals
self.addEventListener('install', function(event) {
    console.log('Service Worker installing.');
});

// eslint-disable-next-line no-restricted-globals
self.addEventListener('activate', function(event) {
    console.log('Service Worker activating.');
});

// eslint-disable-next-line no-restricted-globals
self.addEventListener('push', function(event) {
    console.log('[Service Worker] Push Received.');
    const pushData = event.data.text();
    console.log(`[Service Worker] Push received this data - "${pushData}"`);
    let data, title, body;
    try {
        data = JSON.parse(pushData);
        title = data.title;
        body = data.body;
    } catch(e) {
        title = "Untitled";
        body = pushData;
    }
    const options = {
        body: body
    };
    console.log(title, options);

    event.waitUntil(
        // eslint-disable-next-line no-restricted-globals
        self.registration.showNotification(title, options)
    );
});